// Render a local Markdown report into inspected pages; no network content.
const fs=require('node:fs'),path=require('node:path');
const {chromium}=require('../../web-estate/sites/aboudy-keddeh/node_modules/playwright');
const file=path.resolve(process.argv[2]);if(!file)throw Error('Report path required');
const text=fs.readFileSync(file,'utf8').replace(/\n---\n[\s\S]*$/,'');
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const chunks=text.split(/(?=^## [0-9]+\.)/m);
const groups=[chunks.slice(0,4).join(''),chunks.slice(4,7).join(''),chunks.slice(7).join('')];
function paragraphs(s){return s.trim().split(/\n\s*\n/).map(p=>p.startsWith('## ')?'<h2>'+escape(p.slice(3))+'</h2>':p.startsWith('# ')?'<h1>'+escape(p.slice(2))+'</h1>':'<p>'+escape(p)+'</p>').join('');}
const html='<!doctype html><html lang="en"><meta charset="utf-8"><title>KEX VFS fault qualification</title><style>@page{size:A4;margin:0}*{box-sizing:border-box}body{margin:0;color:#142736;font-family:Arial,sans-serif}.sheet{width:210mm;height:297mm;padding:17mm 18mm;break-after:page;position:relative;background:white}.sheet:last-child{break-after:auto}header{font-size:10px;border-bottom:2px solid #245e6c;padding-bottom:8px;letter-spacing:.5px}h1{font-size:20px;line-height:1.15}h2{font-size:13px;margin:15px 0 6px}p{font-size:10.5px;line-height:1.4;margin:8px 0}footer{position:absolute;bottom:10mm;left:18mm;right:18mm;font-size:9px;border-top:1px solid #80949a;padding-top:6px}.body{max-height:250mm;overflow:visible}</style>'+groups.map((g,i)=>'<section class="sheet"><header>KEDDEH SYSTEMS · RESEARCH & DEVELOPMENT · ENGINEERING DRAFT</header><div class="body">'+paragraphs(g)+'</div><footer>© 2026 A. Keddeh · Reserved report rights · KEX-RD-VFS-FAULT-20261008-001 · v0.1 · '+(i+1)+'/3</footer></section>').join('')+'</html>';
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',chromiumSandbox:false});try{const page=await browser.newPage({viewport:{width:1000,height:1200}});await page.route('**/*',r=>r.abort());await page.setContent(html);const sheets=page.locator('.sheet');for(let i=0;i<3;i++){const bounds=await sheets.nth(i).locator('.body').evaluate(e=>({bottom:e.getBoundingClientRect().bottom,limit:e.closest('.sheet').querySelector('footer').getBoundingClientRect().top}));if(bounds.bottom>bounds.limit)throw Error('Page content overlaps footer '+i);await sheets.nth(i).screenshot({path:path.join(path.dirname(file),'REPORT_PAGE_'+(i+1)+'.png')});}fs.writeFileSync(path.join(path.dirname(file),'REPORT.html'),html);await page.pdf({path:path.join(path.dirname(file),'REPORT.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,tagged:true,outline:true});console.log('Rendered 3 pages; no content/footer overlap');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
